-- Run once in the Supabase SQL Editor before starting the API.
create extension if not exists "pgcrypto";
create type user_role as enum ('researcher', 'scientist', 'admin');
create type resource_type as enum ('report', 'publication', 'dataset', 'photo', 'video', 'outreach', 'institutional');
create table users (id uuid primary key default gen_random_uuid(), username varchar(80) unique not null, email varchar(255) unique not null, password_hash varchar(255), full_name varchar(160), role user_role not null default 'researcher', avatar_url text, last_login timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table resources (id uuid primary key default gen_random_uuid(), title varchar(500) not null, description text, resource_type resource_type not null, category varchar(100), research_area varchar(160), author varchar(255), institution varchar(255), publication_date date, location varchar(255), latitude double precision, longitude double precision, tags jsonb not null default '[]', file_url text, thumbnail_url text, external_url text, metadata jsonb not null default '{}', view_count integer not null default 0, created_at timestamptz default now(), updated_at timestamptz default now());
create index idx_resources_type on resources(resource_type); create index idx_resources_area on resources(research_area); create index idx_resources_date on resources(publication_date desc);
create table collections (id uuid primary key default gen_random_uuid(), user_id uuid not null references users(id) on delete cascade, name varchar(160) not null, description text, created_at timestamptz default now(), updated_at timestamptz default now());
create table collection_items (collection_id uuid references collections(id) on delete cascade, resource_id uuid references resources(id) on delete cascade, created_at timestamptz default now(), primary key(collection_id, resource_id));
create table citizen_projects (id uuid primary key default gen_random_uuid(), title varchar(300) not null, description text not null, status varchar(50) not null default 'active', created_by uuid not null references users(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table citizen_submissions (id uuid primary key default gen_random_uuid(), project_id uuid not null references citizen_projects(id) on delete cascade, user_id uuid not null references users(id), observation text not null, latitude double precision, longitude double precision, metadata jsonb not null default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
-- Enable RLS and add policies appropriate to your deployment before exposing tables through Supabase APIs.
